### ISSUE TITLE
[Proposal] Rewritten core in typescript

### ISSUE THREAD

**Issue by SukkaW** [DIYgod/RSSHub#7531]
RT. Why not?

## To-Do List

- [ ] Update all workflow related tools
  - [ ] ESLint configuration (IMHO we should have `eslint-config-rsshub`)
  - [ ] Create a `tsconfig.json`
- [ ] Migrate all [`utils`](https://github.com/DIYgod/RSSHub/tree/master/lib/utils) to typescript, along with [typedoc](https://typedoc.org/) compatible comment.
- [ ] Migrate all our [middlewares](https://github.com/DIYgod/RSSHub/tree/master/lib/middleware) to typescript
- [ ] Migrate [the rest of the core](https://github.com/DIYgod/RSSHub/tree/master/lib) into typescript
- [ ] Migrate unit test into typescript

We will leave all routes in `js` for now, for easier rule contribution.

**Comment by TonyRL** [comment]
Closed in #14295.
